%% build_windows_dll.m

clear;
clc;


%% 1. 基本参数

maximumSignalLength = 16384;


%% 2. DLL 配置

cfg = coder.config( ...
    'dll', ...
    'ecoder', ...
    false ...
);

cfg.TargetLang = 'C++';

cfg.GenerateReport = true;

cfg.BuildConfiguration = ...
    'Faster Runs';

cfg.EnableDynamicMemoryAllocation = true;


%% 3. 添加 C ABI wrapper

wrapperDirectory = ...
    fullfile(pwd, 'native_api');

cfg.CustomInclude = ...
    wrapperDirectory;

cfg.CustomSource = ...
    fullfile( ...
        wrapperDirectory, ...
        'iq_feature_c_api.cpp' ...
    );


%% 4. MATLAB 入口输入类型

iDataType = ...
    zeros( ...
        maximumSignalLength, ...
        1, ...
        'single' ...
    );

qDataType = ...
    zeros( ...
        maximumSignalLength, ...
        1, ...
        'single' ...
    );

signalLengthType = ...
    int32(0);

sampleRateType = ...
    double(0);

args = { ...
    iDataType, ...
    qDataType, ...
    signalLengthType, ...
    sampleRateType ...
};


%% 5. 输出目录

outputDirectory = ...
    fullfile( ...
        pwd, ...
        'build', ...
        'windows_x86_64' ...
    );

if ~exist(outputDirectory, 'dir')
    mkdir(outputDirectory);
end


%% 6. 生成 C++ DLL

codegen( ...
    'extractAllFeatures', ...
    '-config', cfg, ...
    '-args', args, ...
    '-d', outputDirectory, ...
    '-report' ...
);